### ISSUE TITLE
Support `cf parse` and `cf race`

### ISSUE THREAD

**Issue by nikhil-sarda** [cpeditor/cpeditor#127]
**Is your feature request related to a problem? Please describe.**
When we use "open contest option",we open multiple files say A,B,C..etc.But when we parse contest using competitive companion,the new tabs of those questions A,B,C gets created.

**Describe the solution you'd like**
My request is to add a feature so that just the update the test cases of the corresponding file name(i.e test cases of A in A.cpp ,B in B.cpp etc) rather than creation of new files(if its already created).This will also help us more during the contest avoiding to select the location all the time.

**Describe alternatives you've considered**

**Additional context**

**Comment by ouuan** [comment]
I think it's better to support CF Tool's `cf parse` and `cf race`.

**Comment by nikhil-sarda** [comment]
> I think it's better to support CF Tool's `cf parse` and `cf race`.

Does this save the newly created file automatically?

**Comment by nikhil-sarda** [comment]
> > I think it's better to support CF Tool's `cf parse` and `cf race`.
> 
> Does this save the newly created file automatically?

I mean if it does, then its better to add this feature and remove "open contest option" as it becomes redundant then?

**Comment by ouuan** [comment]
No, CP is not CF only, and Open Contest is not designed for CF.

It's easier to support `cf parse` and `cf race` than support what you request.

**Comment by ouuan** [comment]
Assigned to @coder3101 because CF is very slow in China without a proxy, but I failed to set proxy for CF Tool, so it's hard for me to test anything related to CF Tool.

**Comment by ouuan** [comment]
I suggest add both actions and command-line options like `--cfrace, --cfparse`.

**Comment by testitem** [comment]
Wait @ouuan how do you set a proxy to CF? I'm in China too

But submitting from cf-tool seems to work at least...

**Comment by ouuan** [comment]
> Wait @ouuan how do you set a proxy to CF? I'm in China too
> 
> But submitting from cf-tool seems to work at least...

Are you Chinese?

It's the same as setting proxy for any other websites.

**Comment by ouuan** [comment]
The workflow should be like this:

1. Implement functions which Use [QProcess](https://doc.qt.io/qt-5/qprocess.html) to run `cf race` and `cf parse` in `src/cf-tools.cpp` (put the definitions in `include/cf-tools.hpp`).

2. Add actions in `ui/appwindow.ui`, define and implement the slots in `*/appwindow.*pp`. You may need [QInputDialog](https://doc.qt.io/qt-5/qinputdialog.html) and [QFileDialog](https://doc.qt.io/qt-5/qfiledialog.html) to get the contest ID and directory to put the files. Use `AppWindow::openTabs(const QStringList &paths)` to  open tabs after the process is finished. You may need to emit a signal from `CFTools` when the process emits the `finished` signal, and connect it the `AppWindow` so that the tabs can be opened.

3. Add [command-line options](https://doc.qt.io/qt-5/qcommandlineparser.html) in `src/main.cc`, add new constructors for `AppWindow`, and use `SingleApplication::sendMessage` to send the arguments, and deal with these arguments in `AppWindow::onReceivedMessage`. Refactor the codes so that you don't need to implement the same arguments parsing in both the constructor and `onReceivedMessage` if you like.

Contributions are welcomed.

**Comment by ouuan** [comment]
It's also good to add the function of [CFBooster](https://github.com/fjzzq2002/CFBooster).

**Comment by ouuan** [comment]
We may no longer specifically support CF Tool after #212 is finished. 

And after #176 is finished, `cf race` can be done by setting the same input/answer file format as CF Tool, and run `cf race && cpeditor cf` or something like that.
