### ISSUE TITLE
Standardize function/variable cases

### ISSUE THREAD

**Issue by testitem** [cpeditor/cpeditor#155]
**Is your feature request related to a problem? Please describe.**
Currently, cp-editor uses:

 1. `camelCase`: `CompanionServer::onReadReady`
 2. `snake_case`: `void AppWindow::on_comment_toggle()`
 3. A mixture of both: `void AppWindow::on_actionCompile_Run_triggered()`

This makes it especially difficult to remember a variable name across files.

**Describe the solution you'd like**
Agree to use camelCase everywhere.

**Describe alternatives you've considered**
~~Agree to use SpONgeBoBCAse everywhere.~~

**Additional context**
none

**Comment by coder3101** [comment]
>     2\. `snake_case`: `void AppWindow::on_comment_toggle()`

Snake case functions are are slots that are generated by Qt MOC(Meta object Compiler). I don't know if there is  way to change it or not. Like for instance in this above function, it means that this function was created from `appwindow.ui` file, as slot when comment (widget) is toggled. 

>     1. `camelCase`: `CompanionServer::onReadReady`

camelCase are slots that are programmatically created by us. We created these slots and we connect them to signals. Most of the Code we have written was camelCase, Code that was auto-generated was snake_case. Probably changing those auto-generated code will be difficult task because we need to manually change things in *.ui files. Changing them manually is discouraged by Qt.

The only way left for us is to make everything snake_case, which to be honest, I don't like at all. On Languages with OOPs, snake_case is horrible. Rest I leave upto you, maybe you could find a way for Qt MOC to genereate camelCase signals.

The only advantage of this mis-match style is that, we quickly get to know how a slot was created.

**Comment by ouuan** [comment]
You can check if every snake_case function is a UI slot. If there are snake_case functions that are not UI slots, please change it. Otherwise, I think we have to keep them.

**Comment by ouuan** [comment]
And we can change mix of both to snake_case only.

**Comment by ouuan** [comment]
snake_case variables can be changed to camelCase, too.

**Comment by ouuan** [comment]
Don't forget to change the corresponding names in `ui/*.ui` files.

**Comment by Ravenclaw-OIer** [comment]
Just as I am getting familiar with Qt developing, can you assign that to me ?

**Comment by Ravenclaw-OIer** [comment]
So should I change all snake_case to camelCase or other way round?

**Comment by coder3101** [comment]
I prefer `camelCase`, So does Qt API have `camelCase` functions. Change to camelcase, make sure that there are some functions (called slot) which are not called by us in the code but are called from .ui files. (mostly such functions are snake_case), change them to camelCase at all 3 places, in Header in Source and in .ui file, you should open .ui file in a text editor and simply Ctrl+F/R for the function. It is just big XML file.

**Comment by coder3101** [comment]
Make sure to run the application after all refactoring, and while running monitor any message emitted in stderr/stdout of application. The error of slots are not hard error (does not fail to compile or crash), rather soft error (feature will not work). So you must see if all functions are invoked correctly after refactoring.

**Comment by ouuan** [comment]
I prefer using pure `snake_case` for UI slots, which must have `on_` and `_clicked` or something like this.

**Comment by coder3101** [comment]
> I prefer using pure `snake_case` for UI slots, which must have `on_` and `_clicked` or something like this.

Doesn't UI slot already have `snake_case` with names like `on_run_button_clicked`?

If however you want to distinguish the UI slot with our own maybe we could add `onUIRunButtonClicked()` 

`UI`, In front means that this slot is attached to UI files. Or otherwise we might have to make our own slots snakecase which are more than UI slots!

**Comment by ouuan** [comment]
There are many `on_camelCase_clicked`.

**Comment by coder3101** [comment]
> There are many `on_camelCase_clicked`.

Okay, I missed that, It is because we have named the widget in UI with camelCase, otherwise Qt by default generates only snakecase slots.

**Comment by coder3101** [comment]
Moreover, why I suggest camelCase is because everywhere in code, we have used camelCase everything (what we have written). Ultimately in some near future we might need to change the complete casing if we insist on using snake_case. It is good Practice to use one casing throughout the workspace, although C++ does not have any particular Preferred case style, most of organization like Google, Microsoft C++ guidelines say to use camelCase.

**Comment by Ravenclaw-OIer** [comment]
So should I change the UI casing?

**Comment by ouuan** [comment]
[Qt example](https://doc.qt.io/qt-5/designer-using-a-ui-file.html#widgets-and-dialogs-with-auto-connect) uses `on_camelCase_clicked`, so let's use `on_camelCase_clicked` then.

**Comment by coder3101** [comment]
Does this decision makes this issue fixed? If not @Ravenclaw-OIer should know what he needs to do to fix it!

**Comment by ouuan** [comment]
> Does this decision makes this issue fixed? If not @Ravenclaw-OIer should know what he needs to do to fix it!

No, there are also some `on_snake_case_clicked`, and `name="snake_case"` without slots in the UI files.

**Comment by Ravenclaw-OIer** [comment]
Making things clear: I need to change everything in `/ui` to `actionCamelCase`, all on-clicked events to `on_camelCase_clicked`, and every other thing to `camelCase`, is that correct?

**Comment by coder3101** [comment]
> Making things clear: I need to change everything in `/ui` to `actionCamelCase`, all on-clicked events to `on_camelCase_clicked`, and every other thing to `camelCase`, is that correct?

Yup!
