### ISSUE TITLE
Search for already existed file represent the current problem ID

### ISSUE THREAD

**Issue by tuwuna** [cpeditor/cpeditor#198]
**Is your feature request related to a problem? Please describe.**

let say I am coding an atcoder problem and I don't feel like finishing it now so I close current tab

when I parse the problem from browser again it create a new arc096_D.cpp

**Describe the solution you'd like**

simply open the old arc096_D.cpp file

rename cf problem from F.cpp to 678F.cpp

**Describe alternatives you've considered**

maybe an option to simply make it A / B / C / D / E / F .cpp only for those who don't like to keep many file

**Comment by ouuan** [comment]
1. You can open the old file, disable "Open new tabs for Competitive Companion" in Preferences, and parse again.

2. You don't need to parse again if "Save and load test cases" is enabled.

3. In order to use CF Tool without Competitive Companion, you can set the problem URL in the right-click menu of the tabs.

So I think it's not very useful. What do you think?

**Comment by ouuan** [comment]
About the file name, you have the freedom to choose the filename, are you suggesting a setting for the default file name?

**Comment by tuwuna** [comment]
_About the file name, you have the freedom to choose the filename, are you suggesting a setting for the default file name?_

yes I do

**Comment by ouuan** [comment]
OK, this is useful when you don't want to search for the file.

**Comment by ouuan** [comment]
Instead of search by the file name, I'd like the feature that binds files with problem URLs.

**Comment by tuwuna** [comment]
ye that will do thanks you :D

**Comment by ouuan** [comment]
Close this in favor of #199 and #200.
