### ISSUE TITLE
Java Error

### ISSUE THREAD

**Issue by derrick20** [cpeditor/cpeditor#224]
When I run the following code:

```java
import java.io.*;
import java.util.*;

class a {
    public static void main(String args[]) throws Exception {
        System.out.println("hello world");
    }
}
```

I get this compiler error: 

```
[Compile Errors] [
Error: Could not find or load main class .private.var.folders.9w.h80k43g90076kwxyrn3x7d5w0000gn.T.CP Editor-cEclVC.sol.java
Caused by: java.lang.ClassNotFoundException: /private/var/folders/9w/h80k43g90076kwxyrn3x7d5w0000gn/T/CP Editor-cEclVC/sol/java
]
```

**Comment by coder3101** [comment]
What OS? what version? On 6.2.2 On Windows, this compiles and runs in my computer

**Comment by coder3101** [comment]
Work on My Linux as well OpenJDK13 and master branch Works as expected.

**Comment by derrick20** [comment]
I'm on a Mac, 10.15.4

**Comment by ouuan** [comment]
Could you reproduce this and upload the log file? You can find the log file by clicking Options->Show Log Files.

**Comment by derrick20** [comment]
[cpeditor-2020-04-08-08-56-45-688-0.log](https://github.com/cpeditor/cpeditor/files/4450573/cpeditor-2020-04-08-08-56-45-688-0.log)

**Comment by coder3101** [comment]
I haven't checked the log (on mobile). The only possible explanation of that fact that it works on windows and Linux but not on mac is attributed to some `#ifdef APPLE` . Maybe for Mac it fails on escaping space or something. 

Maybe, but I will soon check it on mac and fix it if I am able to reproduce it.

@derrick20 Could you also provide JDK version and vendo? Or how you installed it, like brew command or something.

**Comment by ouuan** [comment]
> The only possible explanation of that fact that it works on windows and Linux but not on mac is attributed to some `#ifdef APPLE` .

There have been many times that the bug on Mac is NOT caused by `#ifdef Q_OS_MACOS`. And he is the only one reported this bug up to now, you can't say this bug happens on macOS only without other's confirmation/testing.

> Maybe, but I will soon check it on mac and fix it if I am able to reproduce it.

"Maybe, but I will" just doesn't make sense. You are always making fake promises.

**Comment by ouuan** [comment]
@derrick20 What's your compile command for Java? (Options->Preferences->Language->Java->Compiler Command)

**Comment by coder3101** [comment]
> You are always making fake promises.

It is just that I am not sure when I will have a mac machine to test, so the uncertainty.

**Comment by coder3101** [comment]
![img](https://i.imgur.com/vsaw1Ry.jpg)

Works fine on macOS 10.15 with `openjdk14` and default Settings and same version as you (6.2.2)

Here are some of the things you can do (in order):
- Reset the Preferences if you changed Java commands.
- Save a file to your Desktop or some other place before compiling it and check if it still errors. Save it on a path with space and another time without space, See if error comes in only one of the above situations.
- Are you able to compile and run in your terminal?
- Try another JDK version (try brew cask install java)
- Since we cannot reproduce it, Can you help us find the issue using [this](https://stackoverflow.com/questions/18093928/what-does-could-not-find-or-load-main-class-mean) and checking your temporary folder that is mentioned in the Error?

If any above method helps you solve the problem, please close this issue leaving a comment on how you solved it. It is important that you share your solution so that others might also be helped as this issue now seems to be specific for your machine.

**Comment by derrick20** [comment]
Ah, I fixed it @ouuan. I switched the compiler command from "javac" to "java," and that worked. It worked when I tested it in terminal, and based on the link you sent @coder3101, running the file with java a.class reproduced the same ClassNotFoundException, so maybe the editor was also doing that?

A different issue I'm having now is that I can't create java files unless I create a contest. When I make a new tab, it defaults to being a cpp file. (That might've contributed to the issue before).

**Comment by ouuan** [comment]
> I switched the compiler command from "javac" to "java," and that worked.

That's strange :thinking: How do you compile and run without CP Editor? Do you use `javac`?

> A different issue I'm having now is that I can't create java files unless I create a contest. If I try to make a singular file with a new tab, it defaults to being a cpp file. (That might've contributed to the issue before).

You can do one of these:

- Set the default language in Preferences->Language->Default Language.
- Switch to another language by the combo box in the top-right corner.
- Create a java file without CP Editor and then open it.
- Save a file with `.java` as the suffix.

**Comment by coder3101** [comment]
> If I try to make a singular file with a new tab, it defaults to being a CPP file.

The default language is set to C++ and you need to change it to Java.  (Preferences->Language->Default Language)

If all these have solved your problem, please close this issue.

**Comment by ouuan** [comment]
> The default language is set to C++ and you need to change it to Java. (Preferences->Language->Default Language)

Duplicate of my reply with more words (compare to "Set the default language in Preferences->Language->Default Language.") and less information (compare to my 4 solutions).

> If all these have solved your problem, please close this issue.

I want to know why setting the compile command to `java` instead of `javac` solves his problem.

**Comment by coder3101** [comment]
> I want to know why setting the compile command to `java` instead of `javac` solves his problem.

@derrick20 Could you please provide output for  `java --version` and `javac --version`?

**Comment by coder3101** [comment]
> Duplicate of my reply with more words (compare to "Set the default language in Preferences->Language->Default Language.") and less information (compare to my 4 solutions).

He seems to be a user who does CP in Java and the only one-shot and best way to set Editor to use java is by changing the default language. Instead of providing too much information, you should provide only sufficient information. This is not about debugging, where you can provide many solutions "try this and try this if that does not work". In this case, all of your 4 solutions will work but the one that will last and is permanent is the "Default language".

**Comment by ouuan** [comment]
> He seems to be a user who does CP in Java and the only one-shot and best way to set Editor to use java is by changing the default language. Instead of providing too much information, you should provide only sufficient information. This is not about debugging, where you can provide many solutions "try this and try this if that does not work". In this case, all of your 4 solutions will work but the one that will last and is permanent is the "Default language".
> 
> So my point of repetition was to re-emphasis on that solution.

It seems that he doesn't know how to change the language of a tab. If you only tell him how to set the default language, when he wants to use C++ for a single problem, he may change the default language to C++ and then back to Java.

**Comment by coder3101** [comment]
Let's leave it to him to decide how he does and what method he chooses. We can't assume his use case. 

@derrick20 To summarize:

- If you want to use Java as your primary language. Set Default Language to Java from Preferences.
- If you want to use other than default language **for a Tab**. On the top right corner of Tab (above Message box) is a button with a language name. It shows the current language that tab is using click on it and change it to Java. This will only change the language for that particular tab only.
- Provide us with the version of java runtime and JDK you are using.
- *Make sure to close this issue, if it fixes your problem*

**Comment by derrick20** [comment]
Ah, that fixed it. Here's my java info.
openjdk 14 2020-03-17
OpenJDK Runtime Environment (build 14+36-1461)
OpenJDK 64-Bit Server VM (build 14+36-1461, mixed mode, sharing)

**Comment by ouuan** [comment]
How do you compile and run without CP Editor? Do you use `javac`?
