### ISSUE TITLE
Increase the tab length for better clarity in code.

### ISSUE THREAD

**Issue by nikhil-sarda** [cpeditor/cpeditor#228]
**Is your feature request related to a problem? Please describe.**
Its not a problem but it would be better if the length by which we are shifted right on pressing enter after "{" is increased.

**Describe the solution you'd like**
The spacing is not that large it can be twice of what it is now for better readability.

**Describe alternatives you've considered**

**Additional context**

**Comment by ouuan** [comment]
Do you mean Preferences->Editor->Tab Length?

**Comment by nikhil-sarda** [comment]
> Do you mean Preferences->Editor->Tab Length?

Exactly...sorry I didn't know about it.

Also i just came up with an idea of auto indenting when we press enter after "if","for" and such branching statement.

**Comment by ouuan** [comment]
> Also i just came up with an idea of auto indenting when we press enter after "if","for" and such branching statement.

See cpeditor/QCodeEditor#1.

**Comment by nikhil-sarda** [comment]
> > Also i just came up with an idea of auto indenting when we press enter after "if","for" and such branching statement.
> 
> See [cpeditor/QCodeEditor#1](https://github.com/cpeditor/QCodeEditor/issues/1).

One query....is there any option(using keyboard) for force closing a tab in the cpeditor window as whenever we close, a tab a window comes for saving it or not?

**Comment by ouuan** [comment]
> One query....is there any option(using keyboard) for force closing a tab in the cpeditor window as whenever we close, a tab a window comes for saving it or not?

1. This is not related to this issue, you'd better ask in the Telegram group.

2. I can't get what you mean. Your sentences don't make sense. I have to guess what you mean. For me, "force closing a tab" and "a window comes for saving it or not" have the opposite meanings.

3. If you mean "How to close an unsaved tab without being asked for whether to save it or not":
   - To close a tab, you can use <kbd>Ctrl+W</kbd>
   - To choose whether to save an unsaved tab or not, use <kbd>S</kbd> or <kbd>D</kbd>

4. If you mean "How to close the whole application with being asked for whether to save each unsaved tab or not and then close all tabs before exiting, instead of loading the tabs in the next session":
    - You can uncheck Preferences->Editor->Hot Exit.
