### ISSUE TITLE
__int128 is not supported

### ISSUE THREAD

**Issue by Mahmud-cse** [cpeditor/cpeditor#259]
I have tried to use __int128. But it failed. Please add this feature as soon as possible.
Thank You

**Comment by coder3101** [comment]
This issue is with your compiler. Use compiler with support for `__int128` type.

Clang provides native support for `__int128`. Please use that compiler. You need to change the compiler command to below after you have `clang` installed and added to PATH.
(Options->Preferences->Languages->C++ Compile command)

Change it to:
```
clang++ -Wall
```

To download clang, use [this link](https://github.com/llvm/llvm-project/releases/download/llvmorg-10.0.0/LLVM-10.0.0-win64.exe)

Once installed add, it to `PATH` usually it installs by default it puts everything at (C://Program Files/LLVM/bin). Add this to your System environment. Make sure you are able to run it from cmd by `clang --version`. You should be able to use `__int128` now.

(Verified on my Windows 10 with clang 9.0.1)

**Comment by Mahmud-cse** [comment]
I have done what u said.But after changing the command to clang++ -Wall
this shows errors. Please help.

**Comment by ouuan** [comment]
No matter what the problem is, it can't be related to CP Editor. Do you know what compiler you used before?

**Comment by Mahmud-cse** [comment]
I am using previous compiler one now.Sent from Mail for Windows 10 From: Yufan YouSent: Sunday, April 26, 2020 6:48 PMTo: cpeditor/cpeditorCc: Mahmud-cse; AuthorSubject: Re: [cpeditor/cpeditor] __int128 is not supported (#259) No matter what the problem is, it can't be related to CP Editor. Do you know what compiler you used before?—You are receiving this because you authored the thread.Reply to this email directly, view it on GitHub, or unsubscribe.

**Comment by Mahmud-cse** [comment]
Can you tell me how can I submit code in codeforce or atcoder from my CP editor.(Windows) Sent from Mail for Windows 10 From: Yufan YouSent: Sunday, April 26, 2020 6:48 PMTo: cpeditor/cpeditorCc: Mahmud-cse; AuthorSubject: Re: [cpeditor/cpeditor] __int128 is not supported (#259) No matter what the problem is, it can't be related to CP Editor. Do you know what compiler you used before?—You are receiving this because you authored the thread.Reply to this email directly, view it on GitHub, or unsubscribe.

**Comment by ouuan** [comment]
> ```<!-- /* Font Definitions */ @font-face {font-family:"Cambria Math"; panose-1:2 4 5 3 5 4 6 3 2 4;} @font-face {font-family:Calibri; panose-1:2 15 5 2 2 2 4 3 2 4;} /* Style Definitions */ p.MsoNormal, li.MsoNormal, div.MsoNormal {margin:0in; margin-bottom:.0001pt; font-size:11.0pt; font-family:"Calibri",sans-serif;} a:link, span.MsoHyperlink {mso-style-priority:99; color:blue; text-decoration:underline;} .MsoChpDefault {mso-style-type:export-only;} @page WordSection1 {size:8.5in 11.0in; margin:1.0in 1.0in 1.0in 1.0in;} div.WordSection1 {page:WordSection1;} -->Can you tell me how can I submit code in codeforce or atcoder from my CP editor.(Windows) Sent from Mail for Windows 10 From: Yufan YouSent: Sunday, April 26, 2020 6:48 PMTo: cpeditor/cpeditorCc: Mahmud-cse; AuthorSubject: Re: [cpeditor/cpeditor] __int128 is not supported (#259) No matter what the problem is, it can't be related to CP Editor. Do you know what compiler you used before?—You are receiving this because you authored the thread.Reply to this email directly, view it on GitHub, or unsubscribe.```

You can reply on GitHub if you can't reply normally from email.

> Can you tell me how can I submit code in codeforce or atcoder from my CP editor.

Read [FAQ](https://github.com/cpeditor/cpeditor#faq) and [Manual](https://github.com/cpeditor/cpeditor/blob/master/doc/MANUAL.md) before asking any more questions.
