### ISSUE TITLE
Export/Import settings

### ISSUE THREAD

**Issue by ouuan** [cpeditor/cpeditor#336]
**Is your feature request related to a problem? Please describe.**

Now it's hard for the user to find the settings file, thus hard to export/import the settings.

**Describe the solution you'd like**

Add "Export settings" and "Import settings" in the "Options" menu of the main window (AppWindow).

We can use `cped` as the extension of the exported file.

**Describe alternatives you've considered**

N/A

**Additional context**

N/A

**Comment by shakeabi** [comment]
Alongside this, we can have "export/import settings" feature. This can help portability of settings?

**Comment by ouuan** [comment]
> Alongside this, we can have "export/import settings" feature. This can help portability of settings?

Export is simply copying the settings file to somewhere else, import is simply pasting another settings file and restart, so I'm wondering if that will be helpful.

BTW, now the settings are saved to the file when exiting, so it will be better if the user can manually save the settings, and it can be automatically done when clicking "reveal the settings file in the file manager".

**Comment by shakeabi** [comment]
I'm just suggesting that the import/export feature more user friendly.

**Comment by coder3101** [comment]
> I'm just suggesting that the import/export feature more user friendly.

It is a good idea, because the editor settings file is hidden be default exporting it can mean copying it to a user chosen location. Like say C://Users/Ashar/backup/settings/cpeditor-settings.cped

`cped` file extension of exported settings, it is so that user cannot open it and change manually potential rendering it unusable. 


Importing a settings will mean a overwrite of current settings, user need to choose the file with extension `cped` and settings will be applied.

This way user can also have a backup at any other location say GitHub or can also be shared.

Another reason for export and import is that, in different OS, the location of settings file is different if a user is willing to use our editor in 2-3 different OS, instead of manually remembering the location in every OS they can simply export/import.

This should be simple and easy to implement as well.

**Comment by ouuan** [comment]
> It is a good idea, because the editor settings file is hidden be default

I missed this point, then I agree that import/export is better.

> exporting it can mean copying it to a user chosen location. Like say C://Users/Ashar/backup/settings/cpeditor-settings.cped
> 
> `cped` file extension of exported settings, it is so that user cannot open it and change manually potential rendering it unusable.
> 
> Importing a settings will mean a overwrite of current settings, user need to choose the file with extension `cped` and settings will be applied.
> 
> This way user can also have a backup at any other location say GitHub or can also be shared.

Why not `ini`? How is `cped` better?

> Another reason for export and import is that, in different OS, the location of settings file is different if a user is willing to use our editor in 2-3 different OS, instead of manually remembering the location in every OS they can simply export/import.

Reveal the settings file in the file manager also solves this.

---

Which of these should we have?

- Reveal the settings file in the file manager
- Save the settings to the settings file
- Export/Import settings

---

Should we validate the settings? I think it won't be an easy job. I think it's OK to ignore the case that the user manually changes some settings and makes it invalid.

**Comment by coder3101** [comment]
> Should we validate the settings?
No, I agree we can ignore the manual modifications. User should not change settings file themselves, if they do, they are responsible for consequences.

---

Export/Import Settings will be best, it fixes all above mentioned issue and I haven't seen application that exposes or reveals settings in file manager.

---

> Why not `ini`? How is `cped` better?

- ini files can be opened as text file and are more easy to edit, just changing the extension to cped makes the exported file a new type unknown to most text editors (like notepad) so it cannot be edited as easily as ini.

- cped will be exclusive to our editor, in a sense that it is associated with our editor, ini is generic and used in general for settings.

- because cped is our extension, we can choose to design it's protocol, in a sense we can Include inside it more than just settings, we can put into it the template source code as well because path of template will be useless if we only copy ini

**Comment by ouuan** [comment]
OK, so we just add import/export with `cped` as the extension.

**Comment by coder3101** [comment]
> OK, so we just add import/export with `cped` as the extension.

Yes as if now, it will be great.
In future we may add template code and other relative settings resources like template code. Inside cped.

**Comment by ouuan** [comment]
@allcontributors add @shakeabi as a contributor for ideas.
