### ISSUE TITLE
Monospace as default font even though its not installed

### ISSUE THREAD

**Issue by sonulohani** [cpeditor/cpeditor#422]
**Describe the bug**

I am running cpeditor in windows 10. The default font looked ugly so I though of changing it. However I noticed that the default font is set to monospace even though the font is not installed.

**To Reproduce**
1. Open cpeditor.
2. Go to Options->Preferences->Appearance
3. **Monospace** font is set to **Editor font**, **Test Case Font** and **Message Logger Font** even though the monospace is not installed.  

**Screenshots**

![image](https://user-images.githubusercontent.com/2958681/85190921-9a538180-b2da-11ea-920d-46b259818c6e.png)

**Environment**

 - OS: Windows 10
 - CP Editor Version: Latest master (6.6.0)

Expected behavior : In windows, **Consolas** is the default monospace font and is what set as default in this editor as well.

**Comment by sonulohani** [comment]
I can work on this issue. Please assign it to me if nobody else is gonna work.

**Comment by coder3101** [comment]
`Consolas` will be good default for Windows, as it comes installed on all Windows and is a mono-spaced font.

**Comment by neko-para** [comment]
@ouuan I don't know how to use allcontributors. Can you do it?

**Comment by ouuan** [comment]
> @ouuan I don't know how to use allcontributors. Can you do it?

You can either read the document of all contributors or read what I commented in issues and pull requests. I did nothing privately, you can see all the operations in the comments.

**Comment by coder3101** [comment]
@all-contributors add @sonulohani for bug

**Comment by coder3101** [comment]
Steps to Reproduce https://github.com/cpeditor/cpeditor/issues/425

- If you have any other non-default font, proceed to next step otherwise set to some other font like "Consolas" and Hit Apply. The Font should change without size change.
- Hit Default for Appearance Settings and Click Apply
- The font text changes to "monospace 12" but the size is not 12 in the editor. A Restart fixes the size.

Reproduced on windows. Will check if reproducible on Linux!

**Comment by ouuan** [comment]
I can confirm that on my Arch Linux with KDE, when resetting to default, the font is actually in the size of the system font.
