### ISSUE TITLE
Only display first <limit> characters if test cases are too long, instead of not loading them

### ISSUE THREAD

**Issue by tuwuna** [cpeditor/cpeditor#487]
**Describe the solution you'd like**

[The testcase file [name.in] || (pasted content) contains more than 5000000 characters, so it only display first 500000 char. The full input is available at name.in. You can change the length limit in Preferences->Advanced->Limits->Test Case Length Limit]

[The output contains more than 500000 characters, so it only display first 5000000. The full output is available at name.out. You can set the output length limit in Preferences->Advanced->Limits->Output Length Limit]

**Comment by ouuan** [comment]
Why do you need an incomplete test case/output?

**Comment by ouuan** [comment]
Compare the first xxx characters?

**Comment by ouuan** [comment]
There are several problems:

1. In order to get AC with incomplete output and answer, your Test Case Length Limit and Output Length Limit needs to be the same, and it's very possible that your output also needs to be exactly the same as the output.
2. The saved test cases are incomplete. It could be confusing if you open this file the next time.
3. It usually doesn't make sense if the input file is incomplete.

So your suggestion can't be the default choice. I also don't think it's very useful to make it optional. According to my experience, setting a bigger limit (perhaps temporarily) is a better choice.

**Comment by ouuan** [comment]
BTW, your issue body, which is two messages, is very confusing. Your title is a little bit better, but "copy-paste, load from file" is not clear enough. What's more, you didn't describe the problem you met, so I have to guess (do you want to compare the incomplete output with the incomplete answer?).

**Comment by tuwuna** [comment]
I want to test how much time my program took or is it RTE, comparing output for big file just to know it is AC or not.

So I want complete input, output but not display all of them (or not display at all) and possibly disable diff checker.

I can use freopen but switching off and on is not a good idea here.

**Comment by ouuan** [comment]
> So I want complete input, output but not display all of them (or not display at all) and possibly disable diff checker.

You should mention this in the issue body.

Then I think the best solution is to provide a way to use two files as the input/answer, and don't display any of input/output/answer.

**Comment by tuwuna** [comment]
Yes that works, also I think it is not usless feature.

**Comment by tuwuna** [comment]
Why hide expected?

**Comment by ouuan** [comment]
I found that it's hard to implement what I described, and it's much easier to implement what @tuwuna described.
