### ISSUE TITLE
Reg: Parenthesis occurence in comments

### ISSUE THREAD

**Issue by AbhayAravinda** [cpeditor/cpeditor#556]
**The Issue:**

Parenthesis within quotations (both single and double quotes) causes some problems in C++. It messes syntax highlighting since they are being used to map opening to closing brackets. Also, if possible, please disable auto-closing of parenthesis while typing within strings.

**To Reproduce**
I've included a sample C++ code
```
# include <bits/stdc++.h>
int main()
{
    std::cout<<"{";
    return 0;
}
```
The **{** present in std out is being mapped to the **}** that ends the main function in syntax highighting

**Environment**

App version: 6.5.4
Git commit hash: 4722e20
Build time: Jul 25 2020 04:22:03
OS: Linux

**Comment by ouuan** [comment]
@allcontributors add @AbhayAravinda as a contributor for reporting bugs.

**Comment by coder3101** [comment]
In addition to this we also need to fix the parentheses highlighting in comments. A parentheses inside a comment should not be highlighted/matched with its opening/closing braces.

**Comment by Ravenclaw-OIer** [comment]
Note: The coloring is correct, but you would get a highlight telling you that it maps with the next `}`.

**Comment by coder3101** [comment]
> Note: The coloring is correct, but you would get a highlight telling you that it maps with the next `}`.

If you want you can contribute to fix this issue by modifying [this](https://github.com/cpeditor/QCodeEditor/blob/40d75a18a0c16f3d9962ca6ede155495069cb96a/src/internal/QCodeEditor.cpp#L420) function for matching braces.

Currently the algorithm works like this:
1. check if character under cursor is a parentheses. If it is we call it `activeSymbol`.
2. Check if it is an opening or closing parentheses. If it is an opening parentheses we need to look for closing parentheses in forward direction, otherwise in backward direction. The parentheses we are looking for is called `counterSymbol`. 
3. Start by setting `counter = 1` and `position = cursor.position()`
4. Loop until we reach end or start of code or counter become zero.
5. Inside loop, if we encounter `counterSymbol`, we decrement counter by one, if we encounter an `activeSymbol`, we increment counter by one, otherwise do nothing just move to next or last character. We update the current position by incrementing or decrementing `position` depending upon direction of movement.
6. After loop, if `counter == 0`, we found the matching parentheses at `position` otherwise there is no matching parentheses.

To fix for ignoring matching parentheses inside quotes. You have to not increment or decrement `counter` if you encounter `activeSymbol` or `counterSymbol` inside quotes. To check if a symbol is inside a quote you can use the same algorithm as above. 

For block comments, you can extend the quote logic by checking `/*` and `*/`, for single line comments, it gets more complicated.

**Comment by coder3101** [comment]
Now quoted parenthesis will not be highlighted. See https://github.com/cpeditor/QCodeEditor/compare/cf9a2179775996a1f7b50764d8c4ca514ec0717a...dad1203cd228378f8e2a8510b5926503813fe0be

Note: Two parenthesis under same quotes or under different quotes will be highlighted. Suppose `|` is cursor.

Nothing is highlighted here
```cpp
int main()
{
auto var = "}|";
}
```

`{` just before `some` will be highlighted.
 
```cpp
int main()
{
auto var = "{ some text }|";
}
```
`{` inside var variable will be highlighted.
```cpp
int main()
{
auto var  = "{";
auto foo ="}|";
}
```

There are some issues with but one thing is for sure that a parenthesis inside quotes will never be matched with a parenthesis outside a quote. 

Anyone is welcome to extend the alogithm mentioned above to improve the matching even further. or extent it to cover block comments and single line comments.
