### ISSUE TITLE
Adding C support

### ISSUE THREAD

**Issue by ahmubashshir** [cpeditor/cpeditor#572]
**Is your feature request related to a problem? Please describe.**

I use C for most of my solutions, but cpeditor doesn't have c in its language selector.

**Describe the solution you'd like**
Support for C

**Comment by ouuan** [comment]
Because most people use one of C++/Java/Python for competitive programming, we won't explicitly support other languages. We might add custom language support in the future, see #371.

If you are using C:

1.  I'm not sure why you want to use C. It's easy to learn basic C++ if you are familiar with C, and many C++ features are very useful in competitive programming.
2.  Most C codes can be compiled by a C++ compiler. You can add `-x c` in the compile command if you want to compile a C code with the `.cpp` extension. Though this doesn't fully solve the problem (for example, CF Tool use the file extension to identify the language of the code, so that it may use C++ to submit), but at least you can compile and run.
