### ISSUE TITLE
Make Window Full Screen with F11 Key

### ISSUE THREAD

**Issue by Gourav-raj** [cpeditor/cpeditor#642]
**For those users who have small screen laptops is their would be a choice to hide all task bar and can go to full screen mode using F11 would help a lot to debug and code in small screen!!**

**Comment by coder3101** [comment]
This should, in theory, not be too challenging to implement -- we can make use of the Qt `showFullScreen` helper: https://doc.qt.io/qt-5/qwindow.html#showFullScreen

The auxiliary challenges are making sure users know how to exit full screen, and ensuring that user do no map <kbd>F11</kbd> to some other action shortcut.

**Comment by coder3101** [comment]
@allcontributors please add @Gourav-raj for idea

**Comment by coder3101** [comment]
This isn't as easy as it seems. Simply adding this has some issues.

```cpp
hotkeys.push_back(new QShortcut(Qt::Key_F11, this, [this]{
    if(!isFullScreen()) showFullScreen();
    else showNormal();
}));
```

The problem is with restoring the window back to its original state. Somehow the restored window isn't maximized if prior to showing Full Screen it was maximized. Also, the animation to show Full screen from maximized window is bad, it first gets small (unmaximized) then it gets to fullscreen. When restoring it back, it becomes small (unmaximized).

There is no problem if the window was unmaximized.

**Comment by coder3101** [comment]
The window follows these states when going in full screen mode:
```
Maximized -> Normal (unmaximized) -> Full Screen
```

When restoring back, it moves from `Full Screen -> Normal (unmaximized).`

Calling `showMaximized()` does not helps either and fails to maximize the window.
