### ISSUE TITLE
In macos, Home and End keys are not correct

### ISSUE THREAD

**Issue by WUST-mengqinyu** [cpeditor/cpeditor#775]
**when I press home key I want to go to the beginning of this line, not to the beginning of the whole file, and end key is just same.**

I tried to use karabiner-Elements to change key-binding but not success.

- os : macOS Big Sur 11.1

**Comment by ouuan** [comment]
This is not handled by CP Editor. It is handled by Qt, and what you described is actually the expected behavior on macOS: https://github.com/qt/qtbase/blob/7ee682a1ddc259225618b57ff00f4c36ff5e724c/src/gui/kernel/qplatformtheme.cpp#L283-L285

I never used macOS, so I don't know much about karabiner-Elements.

**Comment by zhou-w-fang** [comment]
Having this issue too... This makes cpeditor very inconvenient to use on macOS.

**Comment by zhou-w-fang** [comment]
@WUST-mengqinyu I managed to use [command + left/right] to replace home/end on macOS.

**Comment by zhou-w-fang** [comment]
@WUST-mengqinyu I managed to use [command + left/right] for home/end in cpeditor on macOS.
