### ISSUE TITLE
Small test cases take nearly the same time as large test cases when running together on Windows

### ISSUE THREAD

**Issue by tiger2005** [cpeditor/cpeditor#789]
I tested a problem with 3 samples. The informations below.
![Z)@HQWTCHUCWWLZ} @TY0SG](https://user-images.githubusercontent.com/41613797/110746149-5264f800-8277-11eb-963f-1f864e70b0a8.png)
![)Q1KV(FJDNFLJZQRW53EK)Y](https://user-images.githubusercontent.com/41613797/110746197-6872b880-8277-11eb-9edc-0140d40655cd.png)
![0TPDCOY0H3A32AI67R2QY)9](https://user-images.githubusercontent.com/41613797/110746198-6872b880-8277-11eb-9b01-c445895db356.png)
But when I run all samples in the same time, the time got wrong.
![J(7MUDG@$OLMR{S Z}PG8EG](https://user-images.githubusercontent.com/41613797/110746602-0070a200-8278-11eb-8d95-150c4954fbbf.png)
After that, I went to Lemonlime and use the same code and samples to test.
![N7FD2{BF@I1PEOQRZ{4~L4I](https://user-images.githubusercontent.com/41613797/110746659-14b49f00-8278-11eb-94b0-264fc7733f07.png)
I am afraid that it will lead to wrong TLE judgement, but I'm not sure. It will be better if the running time can be similar to Lemonlime.

**Comment by coder3101** [comment]
The execution time is just to give a general idea about the complexity of code and it should never be taken seriously. (If your code takes 10 sec to run locally you can expect it to fail on problem with time limit 2sec).

1. If you run same test case again, you will get different time because of how cpu schedule a process and how much cpu time the process gets. 

2. Online judges use server grade processor which are far better than your local hardware. There is a lot of factor that affects execution time of a program.

So take execution time as **time it takes to run the program on your computer with its present state**, present state is the total running process, network state, state of each process and cpu state.

**Comment by ouuan** [comment]
BTW, you can set default time limit in Preferences or for each tab in the context menu of the tabs.

**Comment by tiger2005** [comment]
Got it thx

**Comment by ouuan** [comment]
I'll reopen this, because this is not only "more time on multiple test cases", it's "nearly the same time on multiple test cases". In the screenshot above, test cases 1 and 3 takes less than 100ms, but all three test cases take ~500ms when running together. I can reproduce this on Windows but not on Arch Linux.

**Comment by ouuan** [comment]
We don't provide accurate time measurement, but this behavior is absolutely unexpected.

**Comment by ouuan** [comment]
This only happens when the content of the test case is large. Maybe this behavior is related: On Windows, run a `while (1)` program on a large test case (maybe >10MB), CP Editor freezes.

**Comment by ouuan** [comment]
I guess `QProcess::write` waits for the program when the written input is large.

**Comment by coder3101** [comment]
`Runner::OnStarted` when `processInput` is big is blocking since `write` returns number of bytes written. We should write it in chunks of 1024 bytes and preferably in a worker thread.

I also notice that Timer are starting way before the actual program starts. The `Timer::start` should be called just before `QProcess::start`.

**Comment by ouuan** [comment]
> I also notice that Timer are starting way before the actual program starts. The `Timer::start` should be called just before `QProcess::start`.

Yeah, I tried to fix this problem by adjusting the timer but nearly in vain. We need to fix it but doesn't matter much (only ~10ms).

**Comment by ouuan** [comment]
> I tried to fix this problem by adjusting the timer but nearly in vain.

1b4d607a827ba6abd9b17e606139d2a87721bdcc

**Comment by ouuan** [comment]
https://github.com/ouuan/cpeditor/commit/e673712a0db14e005076e72041aacc12fb3e65a9 doesn't work.

**Comment by ouuan** [comment]
Finally, cac37ffdc7fd2f05880f9ee5b7107af883d182de fixes the problem.
