### ISSUE TITLE
Syntax highlighting has problems handling parentheses.

### ISSUE THREAD

**Issue by tfia** [cpeditor/cpeditor#815]
**Describe the bug**

The editor should highlight the matching parentheses. However, it has problems handling the parentheses between quotation marks. The unmatching parenthese would be highlighted, while the correct matching parentheses wouldn't be highlighted.

**To Reproduce**

If you write something like this, you will find the paranthese between the quotation marks and the first paranthese are highlighted.

`if(a == ')') return '(';`

**Screenshots**

![image.png](https://i.loli.net/2021/04/29/fnTE1vloURmjqC2.png)

**Environment**

 - OS: Windows 10
 - CP Editor Version: 6.7.2

**Comment by Ravenclaw-OIer** [comment]
Known bug, cannot be fixed until we shift to KSyntaxHighlight

**Comment by coder3101** [comment]
> Known bug, cannot be fixed until we shift to KSyntaxHighlight

This isn't related with highlighting. There was a bug in original QCodeEditor `highlightParenthesis()` function which caused these issues.

This issue was patched in [this commit](https://github.com/cpeditor/QCodeEditor/pull/28/commits/dad1203cd228378f8e2a8510b5926503813fe0be) but since it is still not in master, this issue is still present. It will be merged to master with #581 but since it is orthogonal to that PR we may cherry pick and merge it to master.
