### ISSUE TITLE
Support update/remove custom checkers

### ISSUE THREAD

**Issue by swiftqwq** [cpeditor/cpeditor#843]
**Is your feature request related to a problem? Please describe.**

Now cpeditor doesn't auto re-compile custom checker when checker's source file changed.

**Describe the solution you'd like**

Provide "Update" and "Delete" buttons next to "Add Checker".

**Describe alternatives you've considered**

**Additional context**

**Comment by ouuan** [comment]
I don't think a "delete" button would be useful, because there's usually only one checker. 

And instead of adding an "update" button, I think we can either check whether the checker has been changed on running or recompile the checker when it's changed on disk.

As for now, users can switch to another checker and switch back to recompile the checker.
