### ISSUE TITLE
Associate source files to open in cpeditor on macOS

### ISSUE THREAD

**Issue by swift-zym** [cpeditor/cpeditor#846]
**Is your feature request related to a problem? Please describe.**

CPEditor doesn't register itself as a cpp file open method , so I can't open cpp files via CPEditor in my file manager.

**Describe the solution you'd like**

Register CPEditor as a cpp file open method.

**Describe alternatives you've considered**

**Additional context**

**Comment by ouuan** [comment]
I haven't used macOS before. Can you select something like "other applications"? Or is it impossible to open cpp files via CP Editor?

**Comment by ouuan** [comment]
However, it will be good to have this association between CP Editor and supported file types on all of Linux, Windows and macOS.

**Comment by swift-zym** [comment]
> I haven't used macOS before. Can you select something like "other applications"? Or is it impossible to open cpp files via CP Editor?

I can do it,and CP Editor launched after that,but it didn't open any file.

**Comment by swift-zym** [comment]
I think CP Editor doesn't listen the `QFileOpenEvent` by now.

**Comment by ouuan** [comment]
CP Editor opens the files in the arguments, which works on both Windows and Linux. As you mentioned it, maybe we should listen the QFileOpenEvent.

**Comment by coder3101** [comment]
@swift-zym  Are you willing to work on this? If so, please let me know so that I can assign it to you.


Helpful links:

[QFileOpenEvent](https://doc.qt.io/qt-5/qfileopenevent.html#details)

[Info.plist reference](https://developer.apple.com/library/archive/documentation/General/Reference/InfoPlistKeyReference/Articles/CoreFoundationKeys.html#//apple_ref/doc/uid/TP40009249-SW1)

@ouuan is detached run working correctly for unsaved C++ ffile on windows?

**Comment by swift-zym** [comment]
> @swift-zym Are you willing to work on this? If so, please let me know so that I can assign it to you.

Yes.

**Comment by ouuan** [comment]
@allcontributors add @swift-zym as a contributor of ideas.
