### ISSUE TITLE
Translate to Chinese Traditional (Taiwan)

### ISSUE THREAD

**Issue by toto6038** [cpeditor/cpeditor#929]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Is this feature provided in the master branch?

- [X] I have checked the changelog

### Describe the feature you'd like

People familiar to Chinese Traditional (Taiwan) can learn more about this project in their native language.

### Are you willing to contribute to this?

- [X] I'm ready to contribute to this (and will open a PR soon)
- [ ] I'd like to have a try (with the help of the maintainers)
- [ ] No, thanks

### Anything else?

I'm currently working on translating README.md, CONTRIBUTING.md, and DONATE.md into Chinese Traditional (Taiwan).

**Comment by toto6038** [comment]
#930

**Comment by coder3101** [comment]
Should be a part of #664, translation is not an issue if someone is working on it. A translation request is a candidate for an issue.

In #664, We can add in description the list of all languages whose translation is required.

**Comment by coder3101** [comment]
I have updated #664, closing this issue now.

**Comment by ouuan** [comment]
> Should be a part of #664, translation is not an issue if someone is working on it

I don't understand how working-in-progress could be the reason to close an issue. Opening an issue before PR is required in [the contributing guidelines](https://github.com/cpeditor/cpeditor/blob/master/CONTRIBUTING.md#before-writing-codes).

And actually, #664 should be a discussion instead of an issue (it was created before Discussions was available), because it can't be closed by a PR.

**Comment by ouuan** [comment]
We can keep #664 open so that contributors can find it at <https://github.com/cpeditor/cpeditor/contribute>. But I think we shouldn't treat it as a real issue. It's just a call for translators.

**Comment by coder3101** [comment]
> We can keep #664 open so that contributors can find it at <https://github.com/cpeditor/cpeditor/contribute>. But I think we shouldn't treat it as a real issue. It's just a call for translators.

Yes, it can be a discussion as well if we can pin it somewhere people can notice easily.

**Comment by coder3101** [comment]
> I don't understand how working-in-progress could be the reason to close an issue

The point is translation is not an issue. The issue titled "Translate to Chinese (Taiwan)" will never be closed because there will be always something to translate since it's changing. 

The only issue that can be fixed or closed related to translation is "Add Chinese (Taiwan) in System languages". Once code changes are done, the issue can be closed and actual translation can be done voluntarily by translators.
