### ISSUE TITLE
Infinite Scrolling, Dark top notch, CF should fetch test-case for failed input in messages section

### ISSUE THREAD

**Issue by codeitram** [cpeditor/cpeditor#963]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Is this feature provided in the master branch?

- [X] I have checked the changelog

### The problem you are facing

1.  There is no infinite scrolling in text editor, which means I always have to write the code looking at bottom of the screen
2. On Submit, CF-tool doesn't show failed testcases, I have to go to website and check it
3. In Windows, though in dark mode top notch is white which is really annoying in night, please change it's color recently sublime did it too.

### Describe the feature you'd like

1. Infinite Scrolling in text editor
2. Show failed test cases in messages when I Submit is clicked.
3. Make top notch also dark when UI is set to dark mode in windows.

### Are you willing to contribute to this?

- [ ] I'm ready to contribute to this (and will open a PR soon)
- [ ] I'd like to have a try (with the help of the maintainers)
- [X] No, thanks

**Comment by ouuan** [comment]
>     1. Infinite Scrolling in text editor

Please check https://cpeditor.org/docs/preferences/appearance/#add-extra-margin-at-the-bottom-of-the-code-editor. No editor supports infinite scrolling. You are only allowed to scroll one screen more.

>     2\. Show failed test cases in messages when I Submit is clicked.

That's out of the scope of CP Editor. You can ask CF Tool or other submission tools to do this.

AFAIK this is limited to upsolving and small test cases only, thus usually unavailable. And I personally recommend you to do stress testing instead of relying on the official test cases. The stress testing results are often more helpful. And in contests like ICPC or IOI, you don't have the test cases.

>     3\. Make top notch also dark when UI is set to dark mode in windows.

The top is controlled by Windows. We can't make it dark. What we might be able to do is hide that top, and design our own top.

An alternative solution is to set the system theme to dark in your Windows settings.

**Comment by ouuan** [comment]
This will be closed because you asked for multiple features in a single issue.

If you still want to request one or more of them, please request each of them in separate new issues.
